[2023-12-16T11:59:06.283+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ops.transform manual__2023-12-16T11:57:21.843732+00:00 [queued]>
[2023-12-16T11:59:06.286+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ops.transform manual__2023-12-16T11:57:21.843732+00:00 [queued]>
[2023-12-16T11:59:06.286+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-16T11:59:06.291+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2023-12-16 11:57:21.843732+00:00
[2023-12-16T11:59:06.298+0000] {standard_task_runner.py:57} INFO - Started process 162 to run task
[2023-12-16T11:59:06.300+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ops', 'transform', 'manual__2023-12-16T11:57:21.843732+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/workflows_2.py', '--cfg-path', '/tmp/tmpcbd820m5']
[2023-12-16T11:59:06.301+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask transform
[2023-12-16T11:59:06.344+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ops.transform manual__2023-12-16T11:57:21.843732+00:00 [running]> on host 80e3f3cdf7f6
[2023-12-16T11:59:06.423+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ops' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T11:57:21.843732+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T11:57:21.843732+00:00'
[2023-12-16T11:59:06.453+0000] {python.py:194} INFO - Done. Returned value was:      empty_slots  free_bikes  ... online  uid
0             25           7  ...   True  251
1             11          14  ...   True  254
2             18           6  ...   True  267
3              4          14  ...   True   54
4             24           1  ...   True  236
..           ...         ...  ...    ...  ...
502           29           1  ...   True  205
503           23          10  ...   True  213
504           13          20  ...   True  346
505           12          11  ...   True   12
506           15          17  ...   True  247

[507 rows x 12 columns]
[2023-12-16T11:59:06.485+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 222, in execute
    return self._handle_output(return_value=return_value, context=context, xcom_push=self.xcom_push)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 254, in _handle_output
    raise AirflowException(
airflow.exceptions.AirflowException: Returned output was type <class 'pandas.core.frame.DataFrame'> expected dictionary for multiple_outputs
[2023-12-16T11:59:06.487+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=data_ops, task_id=transform, execution_date=20231216T115721, start_date=20231216T115906, end_date=20231216T115906
[2023-12-16T11:59:06.492+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task transform (Returned output was type <class 'pandas.core.frame.DataFrame'> expected dictionary for multiple_outputs; 162)
[2023-12-16T11:59:06.514+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T11:59:06.535+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
