[2023-12-16T11:57:30.329+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ops.extract manual__2023-12-16T11:57:21.843732+00:00 [queued]>
[2023-12-16T11:57:30.345+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ops.extract manual__2023-12-16T11:57:21.843732+00:00 [queued]>
[2023-12-16T11:57:30.346+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-16T11:57:30.364+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2023-12-16 11:57:21.843732+00:00
[2023-12-16T11:57:30.420+0000] {standard_task_runner.py:57} INFO - Started process 130 to run task
[2023-12-16T11:57:30.449+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ops', 'extract', 'manual__2023-12-16T11:57:21.843732+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/workflows_2.py', '--cfg-path', '/tmp/tmpa_6yy51o']
[2023-12-16T11:57:30.451+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask extract
[2023-12-16T11:57:30.598+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ops.extract manual__2023-12-16T11:57:21.843732+00:00 [running]> on host 80e3f3cdf7f6
[2023-12-16T11:57:30.692+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ops' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T11:57:21.843732+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T11:57:21.843732+00:00'
[2023-12-16T11:57:30.715+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/workflows_2.py", line 53, in extract
    response = requests.get(base_url)
NameError: name 'requests' is not defined
[2023-12-16T11:57:30.736+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=data_ops, task_id=extract, execution_date=20231216T115721, start_date=20231216T115730, end_date=20231216T115730
[2023-12-16T11:57:30.753+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task extract (name 'requests' is not defined; 130)
[2023-12-16T11:57:30.780+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T11:57:30.805+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
